name: Build Android APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Godot
      uses: firebelley/godot-export@v5
      with:
        godot_version: 4.2.2
        godot_export_template_version: 4.2.2-stable
        platform: android
        project_path: .
        cache: true
        export_debug: true
